global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "web"
    static_configs:
      - targets: ["web:5000"]

  - job_name: "api"
    static_configs:
      - targets: ["api:5001"]

  - job_name: "postgres"
    static_configs:
      - targets: ["db-exporter:9187"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]



